### ISSUE TITLE
Components' children are not handled properly

### ISSUE THREAD

**Issue by pbellon** [fazouane-marouane/remark-jsx#1]
## Description
When we try to add children to a component in markdown the parser doesn't create the appropriate children. Instead, the components' children are outside the component node's children, at the same depth in the HAST tree.

## Example
```js
const unified = require('unified')
const parse = require('remark-parse')
const customElementCompiler = require('@dumpster/remark-custom-element-to-hast')
const md = `This is a test <MyComponent>of how components' children</MyComponent> are handled`

const parser = unified()
  .use(parse)
  .use(customElementCompiler, { whitelist: ['MyComponent'] })

const hast = parser.processSync(md)

console.log(JSON.stringify(hast, null, 2))
```
Outputs: 
```json
{
  "type": "root",
  "children": [
    {
      "type": "element",
      "tagName": "p",
      "properties": {},
      "children": [
        {
          "type": "text",
          "value": "This is a test "
        },
        {
          "type": "element",
          "tagName": "mycomponent",
          "properties": {},
          "children": []
        },
        {
          "type": "text",
          "value": "of how components' "
        },
        {
          "type": "element",
          "tagName": "strong",
          "properties": {},
          "children": [
            {
              "type": "text",
              "value": "children"
            }
          ]
        },
        {
          "type": "root",
          "children": [],
          "data": {
            "quirksMode": false
          }
        },
        {
          "type": "text",
          "value": " are handled"
        }
      ]
    }
  ]
}
```

## Expected behavior
In my opinion, the previous code should output this:
```json
{
  "type": "root",
  "children": [
    {
      "type": "element",
      "tagName": "p",
      "properties": {},
      "children": [
        {
          "type": "text",
          "value": "This is a test "
        },
        {
          "type": "element",
          "tagName": "mycomponent",
          "properties": {},
          "children": [
            {
              "type": "text",
              "value": "of how components' "
            },
            {
              "type": "element",
              "tagName": "strong",
              "properties": {},
              "children": [
                {
                  "type": "text",
                  "value": "children"
                }
              ]
            }
          ]
        },
        {
          "type": "root",
          "children": [],
          "data": {
            "quirksMode": false
          }
        },
        {
          "type": "text",
          "value": " are handled"
        }
      ]
    }
  ]
}
```

**Comment by fazouane-marouane** [comment]
Thanks for submitting the issue. I'll take a look at it in a few hours.

**Comment by fazouane-marouane** [comment]
Hi,

I've pushed a new package version with the requested fix. For now, the new parsing technique do not play nicely with nested self closing tags. I opened a new issue to track this https://github.com/fazouane-marouane/remark-jsx/issues/2.
Please tell whether this fixes this issue as expected. 😊

**Comment by pbellon** [comment]
Hello, I've updated to 0.4.0 in my small test but it doesn't seem to change anything :/
I created a micro repo [here](https://github.com/pbellon/test-remark-jsx) if you want to check the code (in `spec/parser.spec.js`). 

Also, I've checked `node_modules` to see if it was properly updated and it's the case but this doesn't change the issue: the component node's children attribute is still an empty array.

**Comment by fazouane-marouane** [comment]
As you probably saw in my pull request, you should use `componentWhitelist` instead of `whitelist`. This will solve the remaining issue you're having.

**Comment by pbellon** [comment]
I see, thanks !

**Comment by pbellon** [comment]
I see, my bad. I've updated my test and now components have children however it doesn't seem to be interpreted as markdown but just as plain text:
```json
{
  "type": "root",
  "children": [{
      "type": "text",
      "children": [{ "type": "text", "value": "This is a test " }]
    },{
      "type": "text",
      "value": "\n"
    },{
      "type": "element",
      "tagName": "MyComponent",
      "properties": {},
      "children": [{
          "type": "text",
          "value": "of how components' **children**"
        }
      ]
    },
    ...
  ]
}
```

However I don't know the difficulty of such parsing so maybe this feature shouldn't/can't be implemented.

**Comment by fazouane-marouane** [comment]
@pbellon Actually I did implement this partially on my local code.
I'll try to have in the next release both nested markdown as well as nested autoclose components. It'll probably be thursday since I won't have free time until then. But it's definitely in the works 😉

**Comment by pbellon** [comment]
@fazouane-marouane that's great ! I'm eager to see that :blush: 
In the meantime I'll update my test to check that with the following cases:
- nested markdown `This is <MyComponent>a **test**</MyComponent>`
- nested components `This is <MyComponent>a <Test>test</Test></MyComponent>`
- autoclosing components (nested or not) `<This/> is <MyComponent>a <Test/></MyComponent>`

I'm wondering if I should test for a mix of the previous cases (e.g `Let's try <MyComponent>[to mix](http://...) features <Test/></MyComponent>`) or if that's not necessary.

**Comment by fazouane-marouane** [comment]
@pbellon that’s great! Yes please! I think it will cover more grounds.

**Comment by fazouane-marouane** [comment]
It should be working seamlessly now.
We even have markdown inside custom elements inside markdown ... etc.
I'll make some Jest tests later.

You can find a fairly complex example + its output here: https://runkit.com/fazouane-marouane/5a2a04ae30176200125f9d6e

**Comment by pbellon** [comment]
Like I said earlier in the week I added [new tests](https://github.com/pbellon/test-remark-jsx/blob/master/spec/parser.spec.js) in prevision of your update but when I tried to update to `0.5.2` it thrown 2 different kind of errors (stack trace bellow) that weren't there before the update (the tests were failing but that was normal). I also tried to downgrade to 0.5.0 like in your example above but got the same errors. 
```
Failures:
1) Components with nested markdown encountered a declaration exception
    TypeError: Cannot read property 'length' of undefined
        at Of.blockCustomElement (.../test-md-parser/node_modules/@dumpster/remark-custom-element-to-hast/custom-element-parser.js:61:48)
        at Of.tokenize [as tokenizeInline] (.../test-md-parser/node_modules/remark-parse/lib/tokenizer.js:103:18)
        at Of.paragraph (.../test-md-parser/node_modules/remark-parse/lib/tokenize/paragraph.js:120:20)
        at Of.tokenize [as tokenizeBlock] (.../test-md-parser/node_modules/remark-parse/lib/tokenizer.js:103:18)
        at Of.parse (.../test-md-parser/node_modules/remark-parse/lib/parse.js:33:20)
        at Function.parse (.../test-md-parser/node_modules/unified/index.js:275:45)
        at pipelineParse (.../test-md-parser/node_modules/unified/index.js:22:16)
        at wrapped (.../test-md-parser/node_modules/trough/index.js:93:19)
        at next (.../test-md-parser/node_modules/trough/index.js:56:24)
        at Object.run (.../test-md-parser/node_modules/trough/index.js:30:10)

2) Autoclosing components encountered a declaration exception
    TypeError: Cannot read property 'push' of undefined
        at tree.children.reduce.nodes (.../test-md-parser/node_modules/@dumpster/remark-custom-element-to-hast/custom-element-parser.js:50:16)
        at Array.reduce (<anonymous>)
        at Of.blockCustomElement (.../test-md-parser/node_modules/@dumpster/remark-custom-element-to-hast/custom-element-parser.js:43:33)
        at Of.tokenize [as tokenizeInline] (.../test-md-parser/node_modules/remark-parse/lib/tokenizer.js:103:18)
        at Of.paragraph (.../test-md-parser/node_modules/remark-parse/lib/tokenize/paragraph.js:120:20)
        at Of.tokenize [as tokenizeBlock] (.../test-md-parser/node_modules/remark-parse/lib/tokenizer.js:103:18)
        at Of.parse (.../test-md-parser/node_modules/remark-parse/lib/parse.js:33:20)
        at Function.parse (.../test-md-parser/node_modules/unified/index.js:275:45)
        at pipelineParse (.../test-md-parser/node_modules/unified/index.js:22:16)
        at wrapped (.../test-md-parser/node_modules/trough/index.js:93:19)
```

**Comment by pbellon** [comment]
After some digging I think it comes from the stop condition & the return value we can see here:
```js
// custom-element-parse.js:46
if (!stop) {
    if (!(n.type === 'element' || (n.type === 'text' && (n.value === ' ' || n.value === '\n')))) {
        return [nodes, true];
     }
    nodes.push(n);
}
```
When the return should be `return { nodes: nodes, stop: true}`

I've edited it right in my node_modules and this fixes my issue. I'll create a pull request for that.
 
**EDIT:** [here it is](https://github.com/fazouane-marouane/remark-jsx/pull/3)
Also, I'm not familiar with Lerna so I prefer to let you do the version number bump :3

**Comment by fazouane-marouane** [comment]
@pbellon Oh nice catch!

**Comment by fazouane-marouane** [comment]
Thanks for the PR! I’ll release a new package later in the night. I’ll probably even setup a CI + deploy chain.

**Comment by pbellon** [comment]
Nice idea ! I didn't want to make a PR with my tests because I don't want to force usage of jasmine or anything but feel free to take my code if you want to.

**Comment by fazouane-marouane** [comment]
Oh yes, the tests would be very much appreciated. Feel free to push a new PR when you find the time. We will change the underlying technologies if needed, but jasmine seems good.

**Comment by pbellon** [comment]
Where should I put them? Under the project's root folder or under `packages/remark-custom-element-to-hast` ?

**Comment by fazouane-marouane** [comment]
Yes I think under ˋpackages/remark-custom-element-to-hast/tests` or something similar.

**Comment by pbellon** [comment]
Ok, I'll do that later in the afternoon !

**Comment by pbellon** [comment]
I've created a new PR for the tests. However they're located under `spec` instead of `tests`, that's the default location for jasmine. Also, I must say that at the time I wrote them it was mostly to cover my own usage of the libray so they're far from covering all use cases 😕

**Comment by fazouane-marouane** [comment]
That’s great! Thanks for your contribution. I’ll add some more tests later.

**Comment by fazouane-marouane** [comment]
Hi,

I found the time to push a new version. I also opened #9 to track the next step of producing jsx in run time as react elements (like you already did) or in build time as code.

I'm closing this issue for now. Feel free to reopen it or open a new issue if you face further limitation/bug. Thanks again 😊
