### ISSUE TITLE
Complex nesting of markdown and component can break parsing

### ISSUE THREAD

**Issue by pbellon** [fazouane-marouane/remark-jsx#10]
I've spotted a new possible issue but I think it's kinda normal because of how markdown is designed. Let's say we want to have a "Note" component that can have nested markdown inside a paragraph without "breaking" it.
For instance: 
```md
# This is a test
Of a complex structure with a <Note text="note component">
## Inside title
Will break the parsing
</Note> inside a paragraph.
```
Would produce
```json
{
  "type": "root",
  "children": [
    {
      "type": "element",
      "tagName": "h1",
      "properties": {},
      "children": [{ "type": "text", "value": "This is a test" }]
    },
    {
      "type": "element",
      "tagName": "p",
      "properties": {},
      "children": [
        {
          "type": "text",
          "value": "Of a complex structure with a "
        },
        {
          "type": "element",
          "tagName": "Note",
          "properties": { "text": "note component" },
          "children": [
            {
              "type": "element",
              "tagName": "h2",
              "properties": {},
              "children": [{ "type": "text", "value": "Inside title" }]
            },
            {
              "type": "element",
              "tagName": "p",
              "properties": {},
              "children": [{ "type": "text", "value": "Will break the parsing" }]
            }
          ]
        },
        {
          "type": "text",
          "value": " inside a paragraph."
        }
      ]
    }
  ]
}
```
But right now this isn't possible and it may be because of the line returns inside the `<Note>` component.

**Comment by fazouane-marouane** [comment]
I think that errors should be a bit explicit. I made an issue to track this: https://github.com/fazouane-marouane/remark-jsx/issues/11

Regarding your example, it's the fact that a `## Inside title` is creating another block. So it's a normal parsing error (that was unreported). I'll check that.

However, the following is clearly an issue:
```md
# This is a test
Of a complex structure with a <Note text="note component">
<h2>Hello</h2>
Will break the parsing
</Note> inside a paragraph.
```

If you replace `h2` with `Stuff`, it parses correctly. It's probably because we didn't remove parsing of raw html. I'll look into it this weekend.
Thanks for reporting the issue ❤️

**Comment by fazouane-marouane** [comment]
I couldn't resist until this weekend to get this fixed 😅

Anyway, you can now use usual html tags as a child of your custom elements when they are inline without breaking paragraphs. So using `<h2>...</h2>` for example will work as expected but `## ` won't/shouldn't. It will work only if the custom element isn't located inside a paragraph block.

Tell if this suits you or if you encounter further issues with this.

**Comment by pbellon** [comment]
👍 Perfect ! That was a workaround I was thinking of: just use plain html inside custom components. It's not a big drawback in my opinion. However I think it must be explained somewhere in the documentation to avoid people having this issue

**Comment by vanbroup** [comment]
I'm trying to use a custom component using to add design instructions to a markdown component but the inner component markdown is only partially handled.

Simple inline markdown works fine:
```html
<ImgSection src='/img/image.jpg' align='left' background="blue">
Test **this should be bold** text
</ImgSection>
```

But a list for example doesn't:
```html
<ImgSection src='/img/image.jpg' align='left' background="blue">
* Option 1
* Option 2
* Option 3
* Option 4
</ImgSection>
```

Also a header is causing problems (as indicated in this issue):
```html
<ImgSection src='/img/image.jpg' align='left' background="blue">
# Header

Section content
</ImgSection>
```

It would be great if we can prevent the usage of html tags as much as possible. Yes using html inside the custom component works fine but you could question why we use markdown in the first place.

@fazouane-marouane do you have any plans to support full markdown inside the custom components?

**Comment by fazouane-marouane** [comment]
@vanbroup actually this issue is about using block markdown elements inside an inline custom element (read custom element inside a paragraph for example). In this case, we cannot use headers. You can’t for example create a header inside a paragraph with plain markdown without using html tags.

That being said, your issue is not related to the current one. It should work, in principal. So I’ll look into it very soon 😉

**Comment by fazouane-marouane** [comment]
@vanbroup I had the time to investigate and as I said earlier it was indeed an unrelated issue.
I pushed a fix and published it on npm.

Thanks for the bug report! Don't hesitate to open an issue if you find a problem with the way we parse things.
