### ISSUE TITLE
[Bug] Tables don't parse well when using custom elements inside a table inside a custom element

### ISSUE THREAD

**Issue by fazouane-marouane** [fazouane-marouane/remark-jsx#17]
```md
<Note>
Heading1   | Heading2 | Heading3
:----------|:--------:|------------:
<Note />   | 10       | 42
Hello      | 12       | <Note>*Hello*</Note>
</Note>
```

It parses the table and its body separately.

**Comment by fazouane-marouane** [comment]
Possible solution: When parsing as block elements, we should ignore inline elements altogether and let recursion do the rest for us.

This may be easy to implement using the regex or while reducing the tokens in the 'smart-html-parser': an element will be considered Block if it either is at the start of the file or preceded by an empty line and the close tag is at the end of the file or followed by an empty line.

**Comment by wooorm** [comment]
Closing due to deprecation. See https://github.com/remarkjs/remark-jsx/issues/22#issuecomment-451562940 for more info.
