### ISSUE TITLE
[Bug] Children props are not applied to component when children is blank

### ISSUE THREAD

**Issue by johno** [fazouane-marouane/remark-jsx#19]
Firstly, thanks for your work on this project. I'm currently tying it into a project, [c8r/markdown](https://github.com/c8r/markdown).

The following sets the `children` to blank:

```jsx
<Foo children='bar' />
```

Looks like that's the result of using the `children` attribute for self closing elements. Perhaps we could check if a `children` prop is passed when the `children` attribute is blank in the HAST?

**Comment by fazouane-marouane** [comment]
Hi and thanks for the kind words and for filing this issue!

That's definitely an issue in the way props/children are passed. This should be easy to fix. I'm adding it to the todos!

**Comment by wooorm** [comment]
Closing due to deprecation. See https://github.com/remarkjs/remark-jsx/issues/22#issuecomment-451562940 for more info.
