### ISSUE TITLE
A .jsx code block

### ISSUE THREAD

**Issue by johno** [fazouane-marouane/remark-jsx#21]
Something I'm toying around with is the idea of a [special `.jsx` code block](https://github.com/c8r/markdown/blob/df7f17b5abacd386dde412e580d621d73e74c651/MDX_SPECIFICATION.md#jsx-blocks). It's contents can always be considered pure jsx and parsed/rendered accordingly.

This, at the very least, could be a solid stop gap for more complex jsx blocks that will be difficult to parse into a markdown block. Things like self closing jsx elements with multiline template strings, etc.

**Comment by fazouane-marouane** [comment]
Hi 👋

Yes this would be possible to support in the current parser but without the imports for now.
I'll need to discuss the import idea before to wrap my head around it 😅

But just for reference, it's already possible to have multilines strings like so:

```
<Hero
  title='Some Title'
  description="
    I'm
  
    a
  
    multiline string
  "
/>
```

**Comment by wooorm** [comment]
Closing due to deprecation. See https://github.com/remarkjs/remark-jsx/issues/22#issuecomment-451562940 for more info.
