### ISSUE TITLE
Keep position info

### ISSUE THREAD

**Issue by fazouane-marouane** [fazouane-marouane/remark-jsx#5]
The current behaviour, is to:
1. automatically remove positions at the end of parsing. This should be removed or made optional.
2. using custom position fields (startsAt, endsAt, innerStartsAt, innerEndsAt). This should be changed to a [more standard way](https://github.com/syntax-tree/unist#position).

**Comment by wooorm** [comment]
Closing due to deprecation. See https://github.com/remarkjs/remark-jsx/issues/22#issuecomment-451562940 for more info.
