### ISSUE TITLE
Increase code coverage

### ISSUE THREAD

**Issue by fazouane-marouane** [fazouane-marouane/remark-jsx#6]
- [x] transform from jasmine into tape (the other remark-* projects use tape)
- [x] report code coverage
- [ ] add more tests cases to increase coverage

**Comment by fazouane-marouane** [comment]
100% code coverage & 96% branch coverage in `remark-custom-element-to-hast`.
I'll add tests for `hast-react-renderer` tomorrow.
I'll also add a `Credits` section to thank all people who contributed code samples.

**Comment by wooorm** [comment]
Closing due to deprecation. See https://github.com/remarkjs/remark-jsx/issues/22#issuecomment-451562940 for more info.
