### ISSUE TITLE
Produce jsx/react elements

### ISSUE THREAD

**Issue by fazouane-marouane** [fazouane-marouane/remark-jsx#9]
# Some options

## 1. Produce jsx code
This can be used as a webpack plugin or something similar.

**TODO**: find similar projects.

## 2. Render HAST as a React component
This option is of a particular interest to [Gatsbyjs](https://github.com/gatsbyjs/gatsby/issues/312).

Prior art: @pbellon's [Skoli-Code/skoli-app-template](https://github.com/Skoli-Code/skoli-app-template/blob/master/src/components/renderHAST.js). As a side note, the project also features a [gatsby plugin](https://github.com/Skoli-Code/skoli-app-template/blob/master/plugins/remark-custom-elements/extend-node-type.js) that uses `remark-custom-element-to-hast`.

**Comment by pbellon** [comment]
Concerning prior art I'd also add the `BodyRenderer` that we can find in phenomic [here](https://github.com/phenomic/phenomic/blob/master/packages/plugin-renderer-react/src/components/BodyRenderer.js). However it's not based on the same object structure (the attributes' names are different) so it cannot be used as-is but I think it's a good example anyway. 

There's also the [markdown-in-js](https://github.com/threepointone/markdown-in-js) library that does a similar job.

**Comment by fazouane-marouane** [comment]
I'll also add some other similar code bases to checkout:
1. [hast-to-hyperscript](https://github.com/syntax-tree/hast-to-hyperscript) which is used by [mapbox/remark-react](https://github.com/mapbox/remark-react/blob/master/index.js) and [remarkjs/remark-html](https://github.com/remarkjs/remark-html). Maybe we can find some gotchas or reuse tests from there.
2. [md-to-react](https://github.com/luiscarli/md-to-react), a webpack loader
3. [storybooks/marksy](https://github.com/storybooks/marksy).

**Comment by fazouane-marouane** [comment]
I pushed few more fixes to the parser and a minimal [renderer](https://www.npmjs.com/package/@dumpster/hast-react-renderer) to react components.

@pbellon Feel free to test it when you have the time! If you think it's conclusive enough, we'll propose something final to Gatsby.

**Comment by fazouane-marouane** [comment]
@pbellon would you like to contribute your gatsby plugin ? Gatsby would be open to host an example project on their repository with a fancy blog post and a comparison table of this project and the other options. The Gatsby plugin would be a step towards this.

For information, on my end, the new parser is good enough to be proposed to be transferred to Remark. I’ll start the discussion with them shortly and I’ll keep you posted.

**Comment by pbellon** [comment]
@fazouane-marouane Sorry I took a long absence from GitHub. 
To answer your question: yes, I would be please to host an example but I need to isolate the code for a proper publication. I'll try to do that this week and keep you updated here.

**Comment by fazouane-marouane** [comment]
@pbellon of course take your time. You can create the plugin under src/packages. And don’t forget to add yourself in the list of authors 😉. For the final example & the article, we can collaborate on it together.

I added so many neat integration to React (already published in v0.7) and I’m very eager to document this to be able to share it with the world 😊 That will be my task this week.

Btw, this repository will join shortly remarkjs organisation (sometimes this weekend) and we can publish the article/examples afterwards if this schedule suites you.

**Comment by wooorm** [comment]
Closing due to deprecation. See https://github.com/remarkjs/remark-jsx/issues/22#issuecomment-451562940 for more info.
